// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decks.sql

package postgres

import (
	"context"
)

const addDeckEntry = `-- name: AddDeckEntry :one
INSERT INTO deck_entries (id, deck_id, template_id, start_x, start_y)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, deck_id, template_id, start_x, start_y
`

type AddDeckEntryParams struct {
	ID         string `json:"id"`
	DeckID     string `json:"deck_id"`
	TemplateID string `json:"template_id"`
	StartX     int32  `json:"start_x"`
	StartY     int32  `json:"start_y"`
}

func (q *Queries) AddDeckEntry(ctx context.Context, arg AddDeckEntryParams) (DeckEntry, error) {
	row := q.db.QueryRow(ctx, addDeckEntry,
		arg.ID,
		arg.DeckID,
		arg.TemplateID,
		arg.StartX,
		arg.StartY,
	)
	var i DeckEntry
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.TemplateID,
		&i.StartX,
		&i.StartY,
	)
	return i, err
}

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (id, user_id, name)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, is_active, total_slots, created_at, updated_at
`

type CreateDeckParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, createDeck, arg.ID, arg.UserID, arg.Name)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsActive,
		&i.TotalSlots,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :exec
DELETE FROM decks
WHERE id = $1
`

func (q *Queries) DeleteDeck(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDeck, id)
	return err
}

const deleteDeckEntries = `-- name: DeleteDeckEntries :exec
DELETE FROM deck_entries
WHERE deck_id = $1
`

func (q *Queries) DeleteDeckEntries(ctx context.Context, deckID string) error {
	_, err := q.db.Exec(ctx, deleteDeckEntries, deckID)
	return err
}

const getActiveDeck = `-- name: GetActiveDeck :one
SELECT id, user_id, name, is_active, total_slots, created_at, updated_at FROM decks
WHERE user_id = $1 AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetActiveDeck(ctx context.Context, userID string) (Deck, error) {
	row := q.db.QueryRow(ctx, getActiveDeck, userID)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsActive,
		&i.TotalSlots,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeckByID = `-- name: GetDeckByID :one
SELECT id, user_id, name, is_active, total_slots, created_at, updated_at FROM decks
WHERE id = $1
`

func (q *Queries) GetDeckByID(ctx context.Context, id string) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeckByID, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsActive,
		&i.TotalSlots,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeckEntries = `-- name: GetDeckEntries :many
SELECT id, deck_id, template_id, start_x, start_y FROM deck_entries
WHERE deck_id = $1
`

func (q *Queries) GetDeckEntries(ctx context.Context, deckID string) ([]DeckEntry, error) {
	rows, err := q.db.Query(ctx, getDeckEntries, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeckEntry
	for rows.Next() {
		var i DeckEntry
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.TemplateID,
			&i.StartX,
			&i.StartY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDecksByUser = `-- name: GetDecksByUser :many
SELECT id, user_id, name, is_active, total_slots, created_at, updated_at FROM decks
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetDecksByUser(ctx context.Context, userID string) ([]Deck, error) {
	rows, err := q.db.Query(ctx, getDecksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.IsActive,
			&i.TotalSlots,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeckActive = `-- name: UpdateDeckActive :one
UPDATE decks
SET is_active = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, is_active, total_slots, created_at, updated_at
`

type UpdateDeckActiveParams struct {
	ID       string `json:"id"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpdateDeckActive(ctx context.Context, arg UpdateDeckActiveParams) (Deck, error) {
	row := q.db.QueryRow(ctx, updateDeckActive, arg.ID, arg.IsActive)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsActive,
		&i.TotalSlots,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
