// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (id, player1_id, player2_id, status, turn_duration)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, player1_id, player2_id, winner_id, status, turn_number, turn_duration, board_state, created_at, updated_at, finished_at
`

type CreateMatchParams struct {
	ID           string `json:"id"`
	Player1ID    string `json:"player1_id"`
	Player2ID    string `json:"player2_id"`
	Status       string `json:"status"`
	TurnDuration int32  `json:"turn_duration"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.ID,
		arg.Player1ID,
		arg.Player2ID,
		arg.Status,
		arg.TurnDuration,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.WinnerID,
		&i.Status,
		&i.TurnNumber,
		&i.TurnDuration,
		&i.BoardState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createMatchAction = `-- name: CreateMatchAction :one
INSERT INTO match_actions (id, match_id, player_id, turn_number, action_type, piece_x, piece_y, target_x, target_y, ability_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, match_id, player_id, turn_number, action_type, piece_x, piece_y, target_x, target_y, ability_id, created_at
`

type CreateMatchActionParams struct {
	ID         string      `json:"id"`
	MatchID    string      `json:"match_id"`
	PlayerID   string      `json:"player_id"`
	TurnNumber int32       `json:"turn_number"`
	ActionType string      `json:"action_type"`
	PieceX     int32       `json:"piece_x"`
	PieceY     int32       `json:"piece_y"`
	TargetX    int32       `json:"target_x"`
	TargetY    int32       `json:"target_y"`
	AbilityID  pgtype.Text `json:"ability_id"`
}

func (q *Queries) CreateMatchAction(ctx context.Context, arg CreateMatchActionParams) (MatchAction, error) {
	row := q.db.QueryRow(ctx, createMatchAction,
		arg.ID,
		arg.MatchID,
		arg.PlayerID,
		arg.TurnNumber,
		arg.ActionType,
		arg.PieceX,
		arg.PieceY,
		arg.TargetX,
		arg.TargetY,
		arg.AbilityID,
	)
	var i MatchAction
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerID,
		&i.TurnNumber,
		&i.ActionType,
		&i.PieceX,
		&i.PieceY,
		&i.TargetX,
		&i.TargetY,
		&i.AbilityID,
		&i.CreatedAt,
	)
	return i, err
}

const finishMatch = `-- name: FinishMatch :one
UPDATE matches
SET status = 'finished', winner_id = $2, finished_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, player1_id, player2_id, winner_id, status, turn_number, turn_duration, board_state, created_at, updated_at, finished_at
`

type FinishMatchParams struct {
	ID       string      `json:"id"`
	WinnerID pgtype.Text `json:"winner_id"`
}

func (q *Queries) FinishMatch(ctx context.Context, arg FinishMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, finishMatch, arg.ID, arg.WinnerID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.WinnerID,
		&i.Status,
		&i.TurnNumber,
		&i.TurnDuration,
		&i.BoardState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, player1_id, player2_id, winner_id, status, turn_number, turn_duration, board_state, created_at, updated_at, finished_at FROM matches
WHERE id = $1
`

func (q *Queries) GetMatchByID(ctx context.Context, id string) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.WinnerID,
		&i.Status,
		&i.TurnNumber,
		&i.TurnDuration,
		&i.BoardState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getUserMatchHistory = `-- name: GetUserMatchHistory :many
SELECT id, player1_id, player2_id, winner_id, status, turn_number, turn_duration, board_state, created_at, updated_at, finished_at FROM matches
WHERE player1_id = $1 OR player2_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetUserMatchHistoryParams struct {
	Player1ID string `json:"player1_id"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) GetUserMatchHistory(ctx context.Context, arg GetUserMatchHistoryParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, getUserMatchHistory, arg.Player1ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Player1ID,
			&i.Player2ID,
			&i.WinnerID,
			&i.Status,
			&i.TurnNumber,
			&i.TurnDuration,
			&i.BoardState,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatchState = `-- name: UpdateMatchState :one
UPDATE matches
SET board_state = $2, turn_number = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, player1_id, player2_id, winner_id, status, turn_number, turn_duration, board_state, created_at, updated_at, finished_at
`

type UpdateMatchStateParams struct {
	ID         string `json:"id"`
	BoardState []byte `json:"board_state"`
	TurnNumber int32  `json:"turn_number"`
}

func (q *Queries) UpdateMatchState(ctx context.Context, arg UpdateMatchStateParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatchState, arg.ID, arg.BoardState, arg.TurnNumber)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.WinnerID,
		&i.Status,
		&i.TurnNumber,
		&i.TurnDuration,
		&i.BoardState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateMatchStatus = `-- name: UpdateMatchStatus :one
UPDATE matches
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, player1_id, player2_id, winner_id, status, turn_number, turn_duration, board_state, created_at, updated_at, finished_at
`

type UpdateMatchStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatchStatus, arg.ID, arg.Status)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.WinnerID,
		&i.Status,
		&i.TurnNumber,
		&i.TurnDuration,
		&i.BoardState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}
