// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pieces.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPieceToUser = `-- name: AddPieceToUser :one
INSERT INTO user_pieces (id, user_id, template_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, template_id, level, obtained_at
`

type AddPieceToUserParams struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	TemplateID string `json:"template_id"`
}

func (q *Queries) AddPieceToUser(ctx context.Context, arg AddPieceToUserParams) (UserPiece, error) {
	row := q.db.QueryRow(ctx, addPieceToUser, arg.ID, arg.UserID, arg.TemplateID)
	var i UserPiece
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateID,
		&i.Level,
		&i.ObtainedAt,
	)
	return i, err
}

const createPieceTemplate = `-- name: CreatePieceTemplate :one
INSERT INTO piece_templates (
    id, name, role, rarity, slot_cost,
    max_hp, attack, armor, attack_range,
    move_range, can_jump, movement_type,
    movement_custom, abilities
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, name, role, rarity, slot_cost, max_hp, attack, armor, attack_range, move_range, can_jump, movement_type, movement_custom, abilities, created_at
`

type CreatePieceTemplateParams struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	Role           string `json:"role"`
	Rarity         string `json:"rarity"`
	SlotCost       int32  `json:"slot_cost"`
	MaxHp          int32  `json:"max_hp"`
	Attack         int32  `json:"attack"`
	Armor          int32  `json:"armor"`
	AttackRange    int32  `json:"attack_range"`
	MoveRange      int32  `json:"move_range"`
	CanJump        bool   `json:"can_jump"`
	MovementType   string `json:"movement_type"`
	MovementCustom []byte `json:"movement_custom"`
	Abilities      []byte `json:"abilities"`
}

func (q *Queries) CreatePieceTemplate(ctx context.Context, arg CreatePieceTemplateParams) (PieceTemplate, error) {
	row := q.db.QueryRow(ctx, createPieceTemplate,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.Rarity,
		arg.SlotCost,
		arg.MaxHp,
		arg.Attack,
		arg.Armor,
		arg.AttackRange,
		arg.MoveRange,
		arg.CanJump,
		arg.MovementType,
		arg.MovementCustom,
		arg.Abilities,
	)
	var i PieceTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Rarity,
		&i.SlotCost,
		&i.MaxHp,
		&i.Attack,
		&i.Armor,
		&i.AttackRange,
		&i.MoveRange,
		&i.CanJump,
		&i.MovementType,
		&i.MovementCustom,
		&i.Abilities,
		&i.CreatedAt,
	)
	return i, err
}

const getPieceTemplate = `-- name: GetPieceTemplate :one
SELECT id, name, role, rarity, slot_cost, max_hp, attack, armor, attack_range, move_range, can_jump, movement_type, movement_custom, abilities, created_at FROM piece_templates
WHERE id = $1
`

func (q *Queries) GetPieceTemplate(ctx context.Context, id string) (PieceTemplate, error) {
	row := q.db.QueryRow(ctx, getPieceTemplate, id)
	var i PieceTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Rarity,
		&i.SlotCost,
		&i.MaxHp,
		&i.Attack,
		&i.Armor,
		&i.AttackRange,
		&i.MoveRange,
		&i.CanJump,
		&i.MovementType,
		&i.MovementCustom,
		&i.Abilities,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPieces = `-- name: GetUserPieces :many
SELECT up.id, up.user_id, up.template_id, up.level, up.obtained_at, pt.name, pt.role, pt.rarity
FROM user_pieces up
JOIN piece_templates pt ON pt.id = up.template_id
WHERE up.user_id = $1
`

type GetUserPiecesRow struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	TemplateID string             `json:"template_id"`
	Level      int32              `json:"level"`
	ObtainedAt pgtype.Timestamptz `json:"obtained_at"`
	Name       string             `json:"name"`
	Role       string             `json:"role"`
	Rarity     string             `json:"rarity"`
}

func (q *Queries) GetUserPieces(ctx context.Context, userID string) ([]GetUserPiecesRow, error) {
	rows, err := q.db.Query(ctx, getUserPieces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPiecesRow
	for rows.Next() {
		var i GetUserPiecesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TemplateID,
			&i.Level,
			&i.ObtainedAt,
			&i.Name,
			&i.Role,
			&i.Rarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPieceTemplates = `-- name: ListPieceTemplates :many
SELECT id, name, role, rarity, slot_cost, max_hp, attack, armor, attack_range, move_range, can_jump, movement_type, movement_custom, abilities, created_at FROM piece_templates
`

func (q *Queries) ListPieceTemplates(ctx context.Context) ([]PieceTemplate, error) {
	rows, err := q.db.Query(ctx, listPieceTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PieceTemplate
	for rows.Next() {
		var i PieceTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Rarity,
			&i.SlotCost,
			&i.MaxHp,
			&i.Attack,
			&i.Armor,
			&i.AttackRange,
			&i.MoveRange,
			&i.CanJump,
			&i.MovementType,
			&i.MovementCustom,
			&i.Abilities,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
