// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"
)

type Querier interface {
	AddDeckEntry(ctx context.Context, arg AddDeckEntryParams) (DeckEntry, error)
	AddPieceToUser(ctx context.Context, arg AddPieceToUserParams) (UserPiece, error)
	CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreateMatchAction(ctx context.Context, arg CreateMatchActionParams) (MatchAction, error)
	CreatePieceTemplate(ctx context.Context, arg CreatePieceTemplateParams) (PieceTemplate, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDeck(ctx context.Context, id string) error
	DeleteDeckEntries(ctx context.Context, deckID string) error
	FinishMatch(ctx context.Context, arg FinishMatchParams) (Match, error)
	GetActiveDeck(ctx context.Context, userID string) (Deck, error)
	GetDeckByID(ctx context.Context, id string) (Deck, error)
	GetDeckEntries(ctx context.Context, deckID string) ([]DeckEntry, error)
	GetDecksByUser(ctx context.Context, userID string) ([]Deck, error)
	GetMatchByID(ctx context.Context, id string) (Match, error)
	GetPieceTemplate(ctx context.Context, id string) (PieceTemplate, error)
	GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserMatchHistory(ctx context.Context, arg GetUserMatchHistoryParams) ([]Match, error)
	GetUserPieces(ctx context.Context, userID string) ([]GetUserPiecesRow, error)
	ListPieceTemplates(ctx context.Context) ([]PieceTemplate, error)
	UpdateDeckActive(ctx context.Context, arg UpdateDeckActiveParams) (Deck, error)
	UpdateMatchState(ctx context.Context, arg UpdateMatchStateParams) (Match, error)
	UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) (Match, error)
	UpdateUserCoins(ctx context.Context, arg UpdateUserCoinsParams) (User, error)
	UpdateUserRank(ctx context.Context, arg UpdateUserRankParams) (User, error)
	UpdateUserXP(ctx context.Context, arg UpdateUserXPParams) (User, error)
}

var _ Querier = (*Queries)(nil)
