// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, firebase_uid)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, firebase_uid, xp, level, rank, coins, gems, created_at, updated_at
`

type CreateUserParams struct {
	ID          string `json:"id"`
	Username    string `json:"username"`
	Email       string `json:"email"`
	FirebaseUid string `json:"firebase_uid"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.FirebaseUid,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirebaseUid,
		&i.Xp,
		&i.Level,
		&i.Rank,
		&i.Coins,
		&i.Gems,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, username, email, firebase_uid, xp, level, rank, coins, gems, created_at, updated_at FROM users
WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirebaseUid,
		&i.Xp,
		&i.Level,
		&i.Rank,
		&i.Coins,
		&i.Gems,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, firebase_uid, xp, level, rank, coins, gems, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirebaseUid,
		&i.Xp,
		&i.Level,
		&i.Rank,
		&i.Coins,
		&i.Gems,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserCoins = `-- name: UpdateUserCoins :one
UPDATE users
SET coins = coins + $2, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, firebase_uid, xp, level, rank, coins, gems, created_at, updated_at
`

type UpdateUserCoinsParams struct {
	ID    string `json:"id"`
	Coins int32  `json:"coins"`
}

func (q *Queries) UpdateUserCoins(ctx context.Context, arg UpdateUserCoinsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserCoins, arg.ID, arg.Coins)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirebaseUid,
		&i.Xp,
		&i.Level,
		&i.Rank,
		&i.Coins,
		&i.Gems,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRank = `-- name: UpdateUserRank :one
UPDATE users
SET rank = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, firebase_uid, xp, level, rank, coins, gems, created_at, updated_at
`

type UpdateUserRankParams struct {
	ID   string `json:"id"`
	Rank string `json:"rank"`
}

func (q *Queries) UpdateUserRank(ctx context.Context, arg UpdateUserRankParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserRank, arg.ID, arg.Rank)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirebaseUid,
		&i.Xp,
		&i.Level,
		&i.Rank,
		&i.Coins,
		&i.Gems,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserXP = `-- name: UpdateUserXP :one
UPDATE users
SET xp = xp + $2, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, firebase_uid, xp, level, rank, coins, gems, created_at, updated_at
`

type UpdateUserXPParams struct {
	ID string `json:"id"`
	Xp int32  `json:"xp"`
}

func (q *Queries) UpdateUserXP(ctx context.Context, arg UpdateUserXPParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserXP, arg.ID, arg.Xp)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirebaseUid,
		&i.Xp,
		&i.Level,
		&i.Rank,
		&i.Coins,
		&i.Gems,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
